# A interface de persistência dos assignments. A implementação SQLite fica na infraestrutura.

from __future__ import annotations

from typing import Protocol

from api.assignments.domain.entities.assignment_entity import Assignment, AssignmentStatus


class IAssignmentRepository(Protocol):
    def add(self, assignment: Assignment) -> int: ...

    def get(self, assignment_id: int) -> Assignment | None: ...

    def list_all(self) -> list[Assignment]: ...

    def list_by_classroom(self, classroom_id: int) -> list[Assignment]: ...

    def remove_all_of_classroom(self, classroom_id: int, removed_at: str) -> None: ...

    def set_status(self, assignment_id: int, status: AssignmentStatus) -> None: ...

    def set_published_model(self, assignment_id: int, model_id: int) -> None: ...
